### ISSUE TITLE
Unable to install latest version from pip on Windows 10

### ISSUE THREAD

**Issue by moi15moi** [dhermes/bezier#301]
### Problem
I am unable to install this package with pip.

It seems to be a similar to this problem, but it is with windows: #282

### My environment
Python version: 3.10.7

### Error
```console
$ python -m pip install --upgrade bezier
Collecting bezier
  Using cached bezier-2021.2.12.tar.gz (313 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [1 lines of output]
      The BEZIER_INSTALL_PREFIX environment variable must be set.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

**Comment by dhermes** [comment]
Totally an issue! I have fixed all of these in `main` I just haven't cut a release in over a year, so sorry!

**Comment by anadodik** [comment]
Facing the same issue on Ubuntu.

**Comment by MaxAndolini** [comment]
> Totally an issue! I have fixed all of these in `main` I just haven't cut a release in over a year, so sorry!

I also have this problem when installing on new devices, when can you update?

**Comment by isdito** [comment]
Hello I have the same problem

**Comment by Eigi** [comment]
Hello, this package is the last that prevents me from switching my production environment to python 3.10. Please make a release soon.

**Comment by dhermes** [comment]
@Eigi I'll do my best this week, thanks for the ping! I just merged #302 to prepare for a release.

**Comment by taychee** [comment]
Hello, is there any updates on this? I still get the same error.
Thanks

**Comment by raphael-foliveira** [comment]
Hi, I'm getting this error too, unfortunately. I've been trying to use python_ghost_cursor, which depends on this project. Thank you for your work!

**Comment by dhermes** [comment]
This is resolved! I just released https://pypi.org/project/bezier/2023.7.28/

I'm happy to re-open the discussion if there are further issues, but preemptively closing for now.
